baseURL = 'https://overthinking-development.blog/'
languageCode = 'en-us'
title = 'Overthinking Development'
theme = 'wipdev'

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
