baseURL = 'https://overthinking-development.blog'
languageCode = 'en-us'
title = 'Overthinking Development'
theme = 'wipdev'

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

[services]
  [services.rss]
    limit = 42

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']

