baseURL = 'https://overthinking-development.blog//'
languageCode = 'en-us'
title = 'wipdev-blog'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/categories/projects'
weight = 19

[[menus.main]]
name = 'Blog'
pageRef = '/categories/blog'
weight = 20

[[menus.main]]
name = 'Tutorials'
pageRef = '/categories/tutorials'
weight = 22

[[menus.main]]
name = 'Series'
pageRef = '/series'
weight = 25

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
