baseURL = 'https://wipdev.netlify.app/'
languageCode = 'en-us'
title = 'wipdev-blog'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'GitHub'
url = 'https://github.com/wipdev-tech'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
